name: Deploy to Sakura VPS

on:
  workflow_dispatch:
  push:
    branches:
      - testappjepx

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        run: |
          echo "GitHub Actions is working!"
          pwd
          ls -la